"""
vss.py — Value of the Stochastic Solution (VSS) estimation.

Theory
------
VSS = EEV - RP

  RP  (Recourse Problem) : out-of-sample expected cost of the SAA policy.
  EEV (Expected result of using the Expected Value solution):
        expected cost of the EV policy, obtained by solving the deterministic
        model with a single "expected-duration" scenario.

Both policies are evaluated on the SAME independent out-of-sample evaluation set
(generated by random sampling, with a seed different from the seeds used to
generate either policy's training scenarios).  Using one shared evaluation set
removes evaluation-sample noise from the VSS difference, so VSS >= 0 holds up to
solver optimality gaps rather than being polluted by two independent sample means.

A large VSS means that explicitly accounting for uncertainty (the stochastic
solution) pays off substantially over the naive deterministic plan.

Both policies are built with the SAME step 1 → 2 → 3 warm-start chain as main.py
(each step seeded from the previous), and the EEV/RP out-of-sample objectives are
stored for *every* step, for *every* waiting list, in one cumulative CSV — the
same upsert-into-one-file pattern main.py uses for objective_breakdown.csv.

Usage
-----
# Default: all waiting lists (4, 7, 10, 13), all three steps, n_train=20:
python src/vss.py

# Restrict to particular waiting lists / change the stochastic sample size:
python src/vss.py --n-train 20 --method lhs --n-prime 10000 --seed 42

Outputs (in output/)
--------------------
  vss_results.csv  — cumulative, keyed by (workload, step); re-running a
                     workload replaces its rows (latest run wins).
      columns: workload, step, ev_obj, saa_obj, ev_gap, saa_gap,
               eev, rp, vss, vss_pct, n_train, method, seed, is_k, n_prime,
               time_step1, time_step2, time_step3, mip_gap
        ev_obj  -- in-sample objective of the EV MILP (single scenario)
        saa_obj -- in-sample objective of the SAA MILP (n_train scenarios)
        eev     -- mean out-of-sample cost of the EV policy
        rp      -- mean out-of-sample cost of the SAA policy
        vss     -- VSS = eev - rp
"""

from __future__ import annotations

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

import pandas as pd

from sampling import generate_scenarios
from saa import (
    load_data,
    simulate_schedule,
    solve_policy_chain,
)

# Steps solved/evaluated together (1 → 2 → 3, each warm-started from the last).
_STEPS = (1, 2, 3)

# Column order for the cumulative VSS results CSV.
_VSS_COLS = [
    "workload", "step",
    "ev_obj", "saa_obj", "ev_gap", "saa_gap",
    "eev", "rp", "vss", "vss_pct",
    "n_train", "method", "seed", "is_k", "n_prime",
    "time_step1", "time_step2", "time_step3", "mip_gap",
]


def _make_configure(time_limits: dict, mip_gap: float):
    """Build a per-step solver-configuration callback for solve_policy_chain.

    Mirrors the parameters used in saa.py / main.py so that the policy produced
    here is constructed identically (step 1 → 2 → 3, each warm-started), with
    main.py's per-step time limits.
    """
    def configure(m, step: int, with_mip_focus: bool = False):
        m.setParam("OutputFlag", 0)
        m.setParam("TimeLimit", time_limits[step])
        if with_mip_focus:
            m.setParam("MIPFocus", 1)
        if step == 3:
            m.setParam("MIPGap", mip_gap)
            m.setParam("Presolve", 2)
            m.setParam("Cuts", 2)
            m.setParam("Heuristics", 0.3)
    return configure


def _eval_policy(m, d_eval, S_eval, pi_eval, P, H, SPECS) -> float:
    """Evaluate a fixed first-stage policy on a shared out-of-sample eval set."""
    if m.SolCount == 0:
        return float("nan")
    return simulate_schedule(
        {k: m._X[k].X for k in m._X},
        {k: m._Y[k].X for k in m._Y},
        {p: m._A[p].X for p in P},
        {k: m._D[k].X for k in m._D},
        d_eval, S_eval, pi_eval, P, H, SPECS,
    )


def write_vss_results(output_dir: str, new_rows: list) -> str:
    """Append/overwrite rows in the cumulative VSS results CSV.

    Rows are keyed by ``(workload, step)``; re-running a workload replaces its
    existing rows (latest run wins) while leaving other workloads untouched —
    the same pattern main.py uses for objective_breakdown.csv.  Returns the path.
    """
    path = os.path.join(output_dir, "vss_results.csv")
    df_new = pd.DataFrame(new_rows, columns=_VSS_COLS)

    if os.path.exists(path):
        try:
            df_old = pd.read_csv(path)
            df_all = pd.concat([df_old, df_new], ignore_index=True)
        except Exception as exc:
            print(f"Could not read existing {path} ({exc}); starting fresh.")
            df_all = df_new
    else:
        df_all = df_new

    df_all = (
        df_all
        .drop_duplicates(subset=["workload", "step"], keep="last")
        .sort_values(["workload", "step"])
        .reset_index(drop=True)
    )
    df_all.to_csv(path, index=False)
    print(f"\nVSS results written to: {path}  ({len(df_all)} rows total)")
    return path


# ── Plot palette (deterministic EV vs stochastic SAA) ────────────────────────
_EEV_COLOR = "#f28e2b"   # EEV — deterministic / expected-value policy
_RP_COLOR  = "#4e79a7"   # RP  — stochastic SAA policy
_VSS_COLOR = "#59a14f"   # VSS — value of the stochastic solution
_STEP_LABELS = {1: "Timing only", 2: "Sequencing + Timing", 3: "Full MILP"}


def plot_vss_results(csv_path: str, output_dir: str) -> None:
    """Plot the cumulative VSS results CSV.

    Produces, in *output_dir*:
      * ``vss_eev_rp_step{step}.png`` — one per step: EEV (deterministic) vs RP
        (stochastic) grouped bars per waiting list; the bar-pair gap *is* the VSS.
      * ``vss_summary.png`` — VSS (= EEV - RP) grouped by waiting list, one bar
        per step, so the value of the stochastic solution is comparable across
        instances and model steps at a glance.
    """
    import matplotlib
    matplotlib.use("Agg")            # headless: write PNG without a display
    import matplotlib.pyplot as plt
    import numpy as np

    df = pd.read_csv(csv_path)
    if df.empty:
        print(f"{csv_path} is empty — nothing to plot.")
        return

    steps = sorted(df["step"].unique())
    bar_w = 0.38

    # ── Per-step EEV vs RP grouped bars ───────────────────────────────────────
    for step in steps:
        df_s = df[df["step"] == step].sort_values("workload")
        wls = df_s["workload"].tolist()
        x = np.arange(len(wls))

        fig, ax = plt.subplots(figsize=(max(6, 1.6 * len(wls) + 3), 5))
        b_eev = ax.bar(x - bar_w / 2, df_s["eev"], bar_w,
                       color=_EEV_COLOR, label="EEV — deterministic (EV)")
        b_rp = ax.bar(x + bar_w / 2, df_s["rp"], bar_w,
                      color=_RP_COLOR, label="RP — stochastic (SAA)")
        ax.bar_label(b_eev, fmt="%.0f", padding=2, fontsize=8)
        ax.bar_label(b_rp, fmt="%.0f", padding=2, fontsize=8)

        # Annotate VSS (and % of EEV) above each workload pair.
        top = max(df_s["eev"].max(), df_s["rp"].max())
        for xi, (_, row) in zip(x, df_s.iterrows()):
            ax.annotate(f"VSS={row['vss']:.0f}\n({row['vss_pct']:.0f}%)",
                        xy=(xi, top * 1.04), ha="center", va="bottom",
                        fontsize=8, color=_VSS_COLOR, fontweight="bold")

        ax.set_xticks(x)
        ax.set_xticklabels([f"wl{w}" for w in wls])
        ax.set_xlabel("Waiting list")
        ax.set_ylabel("Out-of-sample objective")
        ax.set_ylim(0, top * 1.18)
        ax.set_title(f"VSS — Step {step} ({_STEP_LABELS.get(step, step)})\n"
                     f"EEV vs RP out-of-sample; gap = VSS")
        # Legend outside the axes so it never overlaps bars or VSS annotations.
        ax.legend(loc="upper left", bbox_to_anchor=(1.01, 1.0), frameon=False)
        ax.grid(axis="y", color="lightgray", linewidth=0.6)
        ax.set_axisbelow(True)
        fig.tight_layout()

        plot_path = os.path.join(output_dir, f"vss_eev_rp_step{step}.png")
        fig.savefig(plot_path, dpi=150, bbox_inches="tight")
        plt.close(fig)
        print(f"VSS plot saved to: {plot_path}")

    # ── Summary: VSS by workload, one bar per step ────────────────────────────
    wls = sorted(df["workload"].unique())
    x = np.arange(len(wls))
    n_steps = len(steps)
    width = 0.8 / n_steps

    fig, ax = plt.subplots(figsize=(max(6, 1.6 * len(wls) + 3), 5))
    for i, step in enumerate(steps):
        df_s = df[df["step"] == step].set_index("workload")
        vals = [float(df_s.loc[w, "vss"]) if w in df_s.index else 0.0 for w in wls]
        dx = (i - (n_steps - 1) / 2) * width
        bars = ax.bar(x + dx, vals, width,
                      label=f"Step {step} ({_STEP_LABELS.get(step, step)})")
        ax.bar_label(bars, fmt="%.0f", padding=2, fontsize=7)

    ax.axhline(0, color="black", linewidth=0.8)
    ax.set_xticks(x)
    ax.set_xticklabels([f"wl{w}" for w in wls])
    ax.set_xlabel("Waiting list")
    ax.set_ylabel("VSS = EEV − RP")
    ax.set_title("Value of the Stochastic Solution by waiting list and step\n"
                 "(negative bars: SAA not solved to optimality — see saa_gap)")
    ax.legend(loc="best", frameon=False)
    ax.grid(axis="y", color="lightgray", linewidth=0.6)
    ax.set_axisbelow(True)
    fig.tight_layout()

    summary_path = os.path.join(output_dir, "vss_summary.png")
    fig.savefig(summary_path, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"VSS summary plot saved to: {summary_path}")


def run_vss_for_wl(wl, args, time_limits, configure):
    """Solve EV + SAA policy chains for one waiting list and return result rows.

    Both policies are built once via the warm-started step 1→2→3 chain
    (``return_all=True`` yields all three step models), then evaluated on the
    shared out-of-sample set for every step.
    """
    print(f"\n{'=' * 65}")
    print(f"  VSS  |  WL {wl}  |  steps {', '.join(map(str, _STEPS))}")
    print(f"{'=' * 65}")

    # 1. Load patient data
    (df, P, H, P0, SPECS, q_pq,
     session_ids, session_sequences, patient_to_h) = load_data(wl)
    print(f"Patients: {len(P)}, Sessions: {len(H)}, Specialties: {SPECS}")

    # 2. Shared out-of-sample evaluation set.  The seed is offset from the
    #    training seed (EV uses no randomness; SAA trains on `seed`) so the
    #    evaluation draw is independent of both policies' training draws.
    d_eval, S_eval, pi_eval = generate_scenarios(
        df, n_scenarios=args.n_prime, method="random",
        seed=args.seed + 99999, is_k=args.is_k,
    )

    # 3. EV policy: single expected-duration scenario, full warm-start chain.
    print("\nSolving EV chain (deterministic, single expected-duration scenario)...")
    d_ev, S_ev, pi_ev = generate_scenarios(
        df, n_scenarios=1, method="expected", seed=args.seed, is_k=args.is_k,
    )
    ev_models = solve_policy_chain(
        P, P0, H, SPECS, q_pq, session_sequences, patient_to_h,
        3, d_ev, S_ev, pi_ev,
        configure, name_prefix=f"EV_wl{wl}", return_all=True,
    )

    # 4. SAA policy: n_train scenarios from the chosen method, full warm-start chain.
    print(f"Solving SAA chain (stochastic, n_train={args.n_train}, "
          f"method={args.method})...")
    d_tr, S_tr, pi_tr = generate_scenarios(
        df, n_scenarios=args.n_train, method=args.method,
        seed=args.seed, is_k=args.is_k,
    )
    saa_models = solve_policy_chain(
        P, P0, H, SPECS, q_pq, session_sequences, patient_to_h,
        3, d_tr, S_tr, pi_tr,
        configure, name_prefix=f"SAA_wl{wl}", return_all=True,
    )

    # 5. Evaluate EEV / RP out-of-sample for every step on the shared eval set.
    rows = []
    for step in _STEPS:
        m_ev, m_saa = ev_models[step], saa_models[step]

        ev_obj  = m_ev.ObjVal  if m_ev.SolCount  > 0 else float("nan")
        saa_obj = m_saa.ObjVal if m_saa.SolCount > 0 else float("nan")
        ev_gap  = m_ev.MIPGap  if m_ev.SolCount  > 0 else float("nan")
        saa_gap = m_saa.MIPGap if m_saa.SolCount > 0 else float("nan")

        eev = _eval_policy(m_ev,  d_eval, S_eval, pi_eval, P, H, SPECS)
        rp  = _eval_policy(m_saa, d_eval, S_eval, pi_eval, P, H, SPECS)
        vss = eev - rp
        vss_pct = (vss / eev * 100.0) if eev else float("nan")

        print(f"  Step {step}: EEV={eev:8.3f}  RP={rp:8.3f}  "
              f"VSS={vss:8.3f}  ({vss_pct:5.1f}% of EEV)"
              + ("   [NOTE: VSS<0 → solver gaps]" if vss < 0 else ""))

        rows.append({
            "workload":   wl,
            "step":       step,
            "ev_obj":     ev_obj,
            "saa_obj":    saa_obj,
            "ev_gap":     ev_gap,
            "saa_gap":    saa_gap,
            "eev":        eev,
            "rp":         rp,
            "vss":        vss,
            "vss_pct":    vss_pct,
            "n_train":    args.n_train,
            "method":     args.method,
            "seed":       args.seed,
            "is_k":       args.is_k,
            "n_prime":    args.n_prime,
            "time_step1": time_limits[1],
            "time_step2": time_limits[2],
            "time_step3": time_limits[3],
            "mip_gap":    args.mip_gap,
        })

    return rows


def main():
    parser = argparse.ArgumentParser(
        description="Compute VSS (EEV, RP) out-of-sample for all steps and "
                    "waiting lists, storing results in one cumulative CSV.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--wl", type=int, nargs="+", default=[4, 7, 10, 13],
                        choices=[4, 7, 10, 13],
                        help="Waiting list(s) to run (default: all four)")
    parser.add_argument("--n-train", type=int, default=20,
                        help="SAA (stochastic) training sample size")
    parser.add_argument("--n-prime", type=int, default=10_000,
                        help="Out-of-sample evaluation set size")
    parser.add_argument("--method", default="lhs", choices=["random", "lhs", "is"],
                        help="Sampling method for the SAA training set")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--is-k", type=float, default=0.5)
    parser.add_argument("--time-step1", type=int, default=60,
                        help="Gurobi time limit (s) for step 1")
    parser.add_argument("--time-step2", type=int, default=60,
                        help="Gurobi time limit (s) for step 2")
    parser.add_argument("--time-step3", type=int, default=300,
                        help="Gurobi time limit (s) for step 3")
    parser.add_argument("--mip-gap", type=float, default=0.05,
                        help="MIP gap for step 3 (matches main.py)")
    parser.add_argument("--output-dir", default=None)
    parser.add_argument("--plot-only", action="store_true",
                        help="Skip solving; just (re)plot the existing "
                             "vss_results.csv in the output dir.")
    args = parser.parse_args()

    root = os.path.join(os.path.dirname(__file__), "..")
    output_dir = args.output_dir or os.path.join(root, "output")
    os.makedirs(output_dir, exist_ok=True)
    csv_path = os.path.join(output_dir, "vss_results.csv")

    # ── Plot-only mode: read the existing CSV and render plots, no solving. ────
    if args.plot_only:
        if not os.path.exists(csv_path):
            print(f"No results to plot: {csv_path} does not exist.")
            return
        plot_vss_results(csv_path, output_dir)
        return

    time_limits = {1: args.time_step1, 2: args.time_step2, 3: args.time_step3}
    configure = _make_configure(time_limits, args.mip_gap)

    all_rows = []
    for wl in args.wl:
        all_rows.extend(
            run_vss_for_wl(wl, args, time_limits, configure)
        )
        # Persist after each waiting list so partial progress survives a crash.
        write_vss_results(output_dir, all_rows)

    # ── Final summary ─────────────────────────────────────────────────────────
    print(f"\n{'=' * 65}")
    print(f"  VSS summary (shared eval set, N'={args.n_prime})")
    print(f"{'=' * 65}")
    print(f"  {'WL':>3}  {'step':>4}  {'EEV':>10}  {'RP':>10}  {'VSS':>10}  {'VSS%':>6}")
    for r in all_rows:
        print(f"  {r['workload']:>3}  {r['step']:>4}  {r['eev']:10.3f}  "
              f"{r['rp']:10.3f}  {r['vss']:10.3f}  {r['vss_pct']:5.1f}%")

    # ── Plots ─────────────────────────────────────────────────────────────────
    plot_vss_results(csv_path, output_dir)


if __name__ == "__main__":
    main()
