"""
vss.py — Value of the Stochastic Solution (VSS) estimation.

Theory
------
VSS = EEV - RP

  RP  (Recourse Problem) : out-of-sample expected cost of the SAA policy.
  EEV (Expected result of using the Expected Value solution):
        expected cost of the EV policy, obtained by solving the deterministic
        model with a single "expected-duration" scenario.

Both policies are evaluated on the SAME independent out-of-sample evaluation set
(generated by random sampling, with a seed different from the seeds used to
generate either policy's training scenarios).  Using one shared evaluation set
removes evaluation-sample noise from the VSS difference, so VSS >= 0 holds up to
solver optimality gaps rather than being polluted by two independent sample means.

A large VSS means that explicitly accounting for uncertainty (the stochastic
solution) pays off substantially over the naive deterministic plan.

Usage
-----
python src/vss.py --step 3 --wl 4 [--n-train 10] [--n-prime 1000] [--seed 42]
                  [--method random] [--time-limit 600] [--mip-gap 0.05]

Outputs (in output/)
--------------------
  vss_wl{wl}_step{step}.csv
      columns: ev_obj, saa_obj, eev, rp, vss
        ev_obj  -- in-sample objective of the EV MILP (single scenario)
        saa_obj -- in-sample objective of the SAA MILP (n_train scenarios)
        eev     -- mean out-of-sample cost of the EV policy
        rp      -- mean out-of-sample cost of the SAA policy
        vss     -- VSS = eev - rp
"""

from __future__ import annotations

import argparse
import csv
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))

import numpy as np
import pandas as pd

from sampling import generate_scenarios
from main import build_model
from saa import (
    load_data,
    simulate_schedule,
    _make_fixed_X,
    _make_fixed_Y,
    _T_START,
    _T_CLOSE,
    _C,
    _BETA,
)


def _configure(m, step: int, time_limit: int, mip_gap: float):
    """Apply solver parameters consistent with saa.py / main.py."""
    m.setParam("OutputFlag", 0)
    m.setParam("TimeLimit", time_limit)
    if step == 3:
        m.setParam("MIPGap", mip_gap)
        m.setParam("Presolve", 2)
        m.setParam("Cuts", 2)
        m.setParam("Heuristics", 0.3)


def _solve_model(
    df, P, P0, H, SPECS, q_pq, session_sequences, patient_to_h,
    step, d, S, pi, time_limit, mip_gap, name,
):
    """Build and solve the step-appropriate model for the given scenario set."""
    fixed_X = _make_fixed_X(P0, H, session_sequences) if step == 1 else None
    fixed_Y = _make_fixed_Y(P, H, patient_to_h)       if step in (1, 2) else None

    m = build_model(
        name, P, P0, H, S, d, pi,
        SPECS, q_pq, _BETA, _T_START, _T_CLOSE, _C,
        fixed_X=fixed_X, fixed_Y=fixed_Y,
    )
    _configure(m, step, time_limit, mip_gap)
    m.optimize()
    return m


def _eval_policy(m, d_eval, S_eval, pi_eval, P, H, SPECS) -> float:
    """Evaluate a fixed first-stage policy on a shared out-of-sample eval set."""
    if m.SolCount == 0:
        raise RuntimeError("Model has no feasible solution; cannot evaluate policy.")
    return simulate_schedule(
        {k: m._X[k].X for k in m._X},
        {k: m._Y[k].X for k in m._Y},
        {p: m._A[p].X for p in P},
        {k: m._D[k].X for k in m._D},
        d_eval, S_eval, pi_eval, P, H, SPECS,
    )


def main():
    parser = argparse.ArgumentParser(description="Compute VSS for a given step/workload.")
    parser.add_argument("--step",       type=int, required=True, choices=[1, 2, 3])
    parser.add_argument("--wl",         type=int, required=True, choices=[4, 7, 10, 13])
    parser.add_argument("--n-train",    type=int, default=10,
                        help="SAA training sample size (default 10)")
    parser.add_argument("--n-prime",    type=int, default=1000,
                        help="Out-of-sample evaluation set size (default 1000)")
    parser.add_argument("--method",     default="random", choices=["random", "lhs", "is"],
                        help="Sampling method for the SAA training set (default random)")
    parser.add_argument("--seed",       type=int,   default=42)
    parser.add_argument("--is-k",       type=float, default=1.0)
    parser.add_argument("--time-limit", type=int,   default=600)
    parser.add_argument("--mip-gap",    type=float, default=0.05)
    parser.add_argument("--output-dir", default=None)
    args = parser.parse_args()

    root = os.path.join(os.path.dirname(__file__), "..")
    output_dir = args.output_dir or os.path.join(root, "output")

    print(f"\n=== VSS  |  Step {args.step}  |  WL {args.wl} ===")

    # 1. Load patient data
    (df, P, H, P0, SPECS, q_pq,
     session_ids, session_sequences, patient_to_h) = load_data(args.wl)
    print(f"Patients: {len(P)}, Sessions: {len(H)}, Specialties: {SPECS}")

    # 2. Shared out-of-sample evaluation set (seed independent of both policies'
    #    training seeds: EV uses no randomness; SAA trains on `seed`).
    d_eval, S_eval, pi_eval = generate_scenarios(
        df, n_scenarios=args.n_prime, method="random",
        seed=args.seed + 99999, is_k=args.is_k
    )

    # 3. EV policy: solve with a single expected-duration scenario
    print("\nSolving EV model (expected-duration scenario)...")
    d_ev, S_ev, pi_ev = generate_scenarios(df, n_scenarios=1, method="expected",
                                           seed=args.seed, is_k=args.is_k)
    m_ev = _solve_model(
        df, P, P0, H, SPECS, q_pq, session_sequences, patient_to_h,
        args.step, d_ev, S_ev, pi_ev,
        args.time_limit, args.mip_gap, name=f"EV_step{args.step}",
    )
    if m_ev.SolCount == 0:
        print("ERROR: EV model returned no feasible solution. Aborting.")
        sys.exit(1)
    ev_obj = m_ev.ObjVal
    eev = _eval_policy(m_ev, d_eval, S_eval, pi_eval, P, H, SPECS)
    print(f"  EV in-sample obj : {ev_obj:.4f}  (gap {m_ev.MIPGap*100:.1f}%)")
    print(f"  EEV (out-of-sample): {eev:.4f}")

    # 4. SAA policy: solve with n_train scenarios from the chosen method
    print(f"\nSolving SAA model (n_train={args.n_train}, method={args.method})...")
    d_tr, S_tr, pi_tr = generate_scenarios(
        df, n_scenarios=args.n_train, method=args.method, seed=args.seed, is_k=args.is_k
    )
    m_saa = _solve_model(
        df, P, P0, H, SPECS, q_pq, session_sequences, patient_to_h,
        args.step, d_tr, S_tr, pi_tr,
        args.time_limit, args.mip_gap, name=f"SAA_step{args.step}",
    )
    if m_saa.SolCount == 0:
        print("ERROR: SAA model returned no feasible solution. Aborting.")
        sys.exit(1)
    saa_obj = m_saa.ObjVal
    rp = _eval_policy(m_saa, d_eval, S_eval, pi_eval, P, H, SPECS)
    print(f"  SAA in-sample obj : {saa_obj:.4f}  (gap {m_saa.MIPGap*100:.1f}%)")
    print(f"  RP (out-of-sample): {rp:.4f}")

    # 5. VSS
    vss = eev - rp
    print(f"\n--- Results (shared eval set, N'={args.n_prime}) ---")
    print(f"  EEV = {eev:.4f}")
    print(f"  RP  = {rp:.4f}")
    print(f"  VSS = {vss:.4f}  ({vss/eev*100:.1f}% of EEV)")
    if vss < 0:
        print("  NOTE: VSS < 0 - attributable to solver optimality gaps "
              "(SAA/EV not solved to optimum).")

    # 6. Write output CSV
    out_path = os.path.join(output_dir, f"vss_wl{args.wl}_step{args.step}.csv")
    with open(out_path, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["ev_obj", "saa_obj", "eev", "rp", "vss"])
        w.writerow([ev_obj, saa_obj, eev, rp, vss])
    print(f"\nResults written to: {out_path}")


if __name__ == "__main__":
    main()
